### ISSUE TITLE
Avoid disposing the HttpClient

### ISSUE THREAD

**Issue by snakefoot** [smashraid/NLog.Splunk#2]
https://github.com/smashraid/NLog.Splunk/blob/f51a01c4caf31cc08cb52ffd43bfa3bbf6a36b48/NLog.Splunk/NLog.Splunk/SplunkTarget.cs#L92

Instead allocate once, and reuse forever. See also -> https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by smashraid** [comment]
Released v1.0.1
