### ISSUE TITLE
Avoid creating string-array for every property-key

### ISSUE THREAD

**Issue by snakefoot** [smashraid/NLog.Splunk#3]
https://github.com/smashraid/NLog.Splunk/blob/f51a01c4caf31cc08cb52ffd43bfa3bbf6a36b48/NLog.Splunk/NLog.Splunk/SplunkTarget.cs#L56

Instead use `string.IndexOf('.') >= 0` to check for dots

**Comment by smashraid** [comment]
Released v1.0.1
